name: clang-format Check
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev , s522 , devfeb2023 ]
  pull_request:
    branches: [ dev , s522 , devfeb2023 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  formatting-dart:
    name: Formatting - Dart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: ''
            exclude: '(CMakeLists.txt|.C|.txt|.for|input|geometry|.hh|.f95|.proto|ext_h101_)' # Exclude file paths containing 
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Mozilla' # optional
